### ISSUE TITLE
Thoughts on using Unreal Engine 4 for the project?

### ISSUE THREAD

**Issue by MaxYari** [REGoth-project/REGoth#103]
Hello there!
First of all I want to say that the fact that you are doing all of this stuff for a gothic engine, like DX11 renderer and now reimplementation -  it's definitely impressive and infinitely respectfull. 
Thank you for spending your time breathing second life into these great rpg's!

So, I hope it will not sound completely silly, but I was wondering, what are your thoughts on using Unreal Engine 4 for this project instead of writing engine from ground zero? 
It has an open code so it's possible to write a parser of gothic files directly in to an engine and attempt to translate all of this to unreal-style logic. 
Ideally I would image big ass parser importing all of the gothic world/mesh/script e.tc files and translating them in to proper unreal engine assets (utopic, I know). 
From a point of my shallow understanding of a matter - there will be no need to worry about rendering side of question, and a complete modern powerfull engine. 

Sounds sane on paper... or not?

**Comment by Tholbrok** [comment]
The goal of the project is re-implementation of gothic engine, it doesn't even make sense to drop all of the current work on the engine and start working on some shitty ue. Do you even see the time that's been already put on this project? I think no. Think rationally.

**Comment by MaxYari** [comment]
"Shitty ue" is not a fair definition of that engine. And your opinion is far from rational thoughts on a matter. "Reimplementation" doesn't imply writing everything from ground zero.

**Comment by MaxYari** [comment]
Also I imagine that such a hypothetical move will not require to "drop all of the current work" as reimplementation of game logic, aprsers of mesh, animation, script files are still valid and can be transfered to 3rd party engine.

**Comment by ousnius** [comment]
The UE4 is amazing, but it really isn't the right thing for this type of project.
What the guys have done here is already amazing and looks more true to the original game than if the UE4 renderer was used.

**Comment by MaxYari** [comment]
True, visually out-of-the-box UE is obviously drasically different, and im not sure if it's even possible to easily tone it down to be more akin to gothic if required (without changing sources). 
My main idea was possible saving of manpower by using already optimised and powerfull engine to handle rendering/visuals.

**Comment by wisien92** [comment]
With reimplementation as I think mods will be supported also - that's a big advantage.

**Comment by Jurigag** [comment]
I think if you will use any 3rd party game engine it can violate gothic license. Even when it will be free and will use game resources.

**Comment by Lehona** [comment]
IANAL, but I'm pretty sure that Andre doesn't need to adhere to any license, because he's not using any licensed material (duh). He's doing a cleanroom implementation of the zEngine and while probably everyone uses the original gothic assets to test / preview stuff, they're not really part of this project and thus don't need to be licensed (everyone that wants to play Gothic in this engine has to provide them himself).

As far as I know he's coding ReGoth because it's fun / a great experience, not because premade engines (like Unity or Irrlicht or UE4 or ...) are not fit for this.
