### ISSUE TITLE
Sometimes need to cancel dialogues in order to get more options

### ISSUE THREAD

**Issue by degenerated1123** [REGoth-project/REGoth#127]
For example when talking to Wolf in Gothic 2. After the first dialogue-choice, only "END" is displayed, but there is more if you talk to him again.

**Comment by markusobi** [comment]
I messed it up when I tried to fix kyle. I reverted the change.
Just fixed Kyle and Rest should be fine.
Fixed with https://github.com/REGoth-project/REGoth/commit/5aa812fa5b1b0bc2598feeb0ef866d3307cd9760
