### ISSUE TITLE
About Android

### ISSUE THREAD

**Issue by RostislavDugin** [REGoth-project/REGoth#135]
In main page of project and Wiki nothing told about Android versions (wiki mentioned directory, but with no description). 

So: 
1. What is the folder "/android"
2. Is real launch game on Android 
3. How build project for Android?

**Comment by Gryxx** [comment]
There is pre-compiled relase for android. https://github.com/REGoth-project/REGoth/releases/tag/0.1.0

**Comment by bukashka101** [comment]
@Gryxx, thanks. I saw this version later, but now about it nowhere written. 

In addition, I try launch this version on my phone, but in doesn't work. If you can, create full manual about installing (maybe, I download incorrect version of Game with unsupported fix or etc.).

**Comment by Gryxx** [comment]
Sorry, I am more familiar with Linux then Android compiling. It would be
nice to have the tutorial.

02.03.2017 7:57 PM "bukashka101" <notifications@github.com> napisał(a):

**Comment by bukashka101** [comment]
@Gryxx, I have Linux in VM, without it I can't work. Sorry, maybe I misunderstood last sentence (I bad speak English): You asked me that I create manual and contribute it? If yes, I can do it, but if you told steps, which I must do for launch game. I try to do steps from pre-release manual, but game doesn't launch.

**Comment by markusobi** [comment]
I recently fixed some compile errors (https://github.com/REGoth-project/REGoth/pull/154), when compiling with sound disabled. Compiling for Android disables sound by default, because sound is not supported for android yet. If you compile REGoth from source, make sure to get the latest version from the master branch, or at least a select a commit, that is after the https://github.com/REGoth-project/REGoth/pull/154 fix.

**Comment by Gryxx** [comment]
@bukashka101
I'm not a native speaker either. I mean I don't have skills to compile
Android version without step-by-step instructions.

**Comment by bukashka101** [comment]
@Gryxx, oh... I something think, that you one of the project developers...

**Comment by degenerated1123** [comment]
Compiling the Android version is not really straight forward, as you need to copy and modify some library-files. I will write a step-by-step guide and simplify the build process a little bit.

Also, the Android version doesn't work for a lot of people, and I couldn't figure out why :/

**Comment by bukashka101** [comment]
@degenerated1123, maybe Android version should do the main direction? For PC exist more similar projects, but for Android — you are one. I know one Russian project (they creates Gothic 2 for Android), which closed, because you done more.

This is project (translate in Google translater second post) — https://vk.com/gothic2android
And in right of cite, in category "ссылки" (translated as "links"), you can find exist builds of game.

**Comment by degenerated1123** [comment]
@bukashka101 I know of that project and found it sad that they had to close. I think it was because of legal issues or something? 

I wouldn't see the android version as the main direction of the project, since it's basically free now that it compiles. It runs exactly the same code as the PC versions.

**Comment by bukashka101** [comment]
@degenerated1123, no, project closed because authors don't want to continue and afraid to tell about it.

So, I wait step-by-step manual and good luck for your project :).

**Comment by bukashka101** [comment]
@degenerated1123, I think that problem in different game versions. In example, in Russia the most popular version with Snowball translate. What version use you and can you give me link to download it (in email or Telegram). Maybe, if install true version - all will work?

**Comment by bukashka101** [comment]
@degenerated1123, hi! I think that problem in different version of games. For example, in Russia the most populast game with Snowball translate. What the version use you and can you give me link for download it (in email or Telegram)? If this resolve problem - I will create pull request with this information, if you want.

**Comment by degenerated1123** [comment]
I currently can't run the engine on my phone at all, since it updated to Android 7. Seems to be a deeper issue. Right now I'm trying one of the newer NDK-versions to see if that helps. 
I've got access to a few more android devices as well now, so I should be able to figure out what went wrong for the people who couldn't load any worlds.

**Comment by bukashka101** [comment]
@degenerated1123, ok. I very grateful for you work at this problem and this very good. Maybe, android emulators like AVD or Genymotion can help you.

**Comment by vice09ita** [comment]
Hello. I ran everything, and for that I thank you .. but I can only move sideways. the controls do not go up and down. you could adjust and put the new apk file available? thanks!!!

**Comment by bukashka101** [comment]
@vice09ita, sorry, can you write name of your device and version of game?

**Comment by vice09ita** [comment]
xiaomi mi mix 1.08

**Comment by vice09ita** [comment]
@degenerated1123 Hi. I ran everything, and for that I thank you .. but I can only move sideways. the controls do not go up and down. you could adjust and put the new apk file available? thanks!!!

**Comment by bukashka101** [comment]
@degenerated1123, Gothic 1, yes? And where you download game? If I launch it — I will try to install buttons for comfort gaming and write about results to you.

**Comment by degenerated1123** [comment]
@vice09ita You should be a able to. The lower left side of the screen is supposed to work like a d-pad. I'm currently on compiling an APK using a newer version of the NDK (Since all previous ones I made seem to crash on Android 7). I'll take a look at the code again, maybe I can spot the mistake :)

**Comment by vice09ita** [comment]
@degenerated1123 I thank you for the answer. unfortunately the lower left side of the screen works only the walk to the right and left. I tried over and over again. the rest, except for the sound, it works. I have a xiaomi mi mix with Android 6.0.1. aspect the new apk with great anticipation.maybe one day you can do something about the fighting. Thank you very much for the good work.

**Comment by vice09ita** [comment]
sorry for my bad English. i write from Italy

**Comment by bukashka101** [comment]
@vice09ita, you use this manual and this version - https://github.com/REGoth-project/REGoth/releases/tag/0.1.0

**Comment by vice09ita** [comment]
bukashka101 yes

**Comment by vice09ita** [comment]
@bukashka101 yes

**Comment by bukashka101** [comment]
@vice09ita, very strange... Something app can't see my REGoth folder... 

Where is folder on your phone? On /storage/emulated/0 or storage/sdcard0? You can see this in explorer. For example, in "File expert" exist function "view folder information".

**Comment by bukashka101** [comment]
@vice09ita, I take all messages in this topic, because I created it :).

**Comment by vice09ita** [comment]
@bukashka101 put all in the root folder. I don't have sdcard,only internal memory.

**Comment by degenerated1123** [comment]
@vice09ita the folder `/sdcard/` automatically links to your internal storage. It's a bit confusing, I know.

Anyways, where the files are put shouldn't matter at all if the input is the only thing that is not working.

**Comment by bukashka101** [comment]
@vice09ita, internal storage has different paths on different system. Word "sdcard" in path `/storage/sdcard0/` - is not external card. I need to know, what is the full path to internal storage in your phone, because in my - it can be another.

**Comment by bukashka101** [comment]
@degenerated1123, some years ago I write application, which had fixed path `/storage/sdcard0`. And I can told that it is not link to internal stororage, if phone has path `/storage/emulated/0`…

**Comment by vice09ita** [comment]
@bukashka101 in my xiaomi is " /sdcard/REGoth " . the 0.1.0 apk version work with controls bug,but the 0.1.1 not working,presents many glitch.

**Comment by bukashka101** [comment]
@vice09ita, thanks! So, my problem can be in path. I try to found this problem in source code. If I launch game - I will try to attach Game Keyboard. It has very more buttons. In diablo 2 in very comfortable

**Comment by vice09ita** [comment]
@bukashka101 I know, but I prefer not to have third-party programs but have everything already in the package, including controls

**Comment by bukashka101** [comment]
@vice09ita, I think that is very hard task. But I am not developer of REGoth and in this case all in hands of @degenerated1123 :)). I can try only this.

**Comment by vice09ita** [comment]
I know quiet. we rely on him!

however works both gothic 1 that gothic 2

**Comment by vice09ita** [comment]
although there is still a lot. for example, the enemies do not attack etc ... But you can explore

**Comment by vice09ita** [comment]
Any news? On android 7 nougat It does not work anymore

**Comment by tomedi** [comment]
Seems that there are some issues regarding to @degenerated1123 last comment on Gitter: 
>oh by the way, I did some stuff regarding the android build. Another pesty piece to work on as it turns out!
I've been using Crystax since it had an updated gcc toolchain and supported up to C++14. However, Crystax isn't updated anymore since google updated their compilers.
And builds using Crystax won't work on Android 7, because it crashes deep inside the locale-code...
So there seems no way around the official NDK (which is good!), but that doesn't play nice with the existing toolchain. I just can't get it to compile right in clang with cmakes official android toolchain :confused:

**Comment by RostislavDugin** [comment]
@markusobi, @degenerated1123, hi! Something changed on Android or all still very bad?

**Comment by degenerated1123** [comment]
Nope, didn't do anything android related!

**Comment by RostislavDugin** [comment]
@degenerated1123, very sad. Some time ago project "Gothic 2 on Android" resumed, but I don't belive in project's developers, because they was making project for two years and lied about finish cause...

**Comment by degenerated1123** [comment]
so, if I understand the post on their site correctly (https://vk.com/gothic2android), they are going to build the game from ground up using unity? Probably using a different story, etc? Google-Translate didn't do too well on that post...

By the way, I'll see if I can get the android-build running again, this time using Android Studio, which is the official way of doing things, I suppose.

**Comment by RostislavDugin** [comment]
@degenerated1123, yes, they try make project in Unity 3D. But they must repaint all world, because Unity has some problems. I think, that it will very long and, in final, thay will not finished this project. So, REGoth more perspective for me.

**Comment by vice09ita** [comment]
@degenerated1123
Someone has new stuff for android? Good news?

**Comment by degenerated1123** [comment]
@vice09ita I patched up the android version to run on the latest master. It also supports downloading of a demo of the game and extracting it. There is no official build yet though, but you can always ask at gitter, if you want an APK.

**Comment by vice09ita** [comment]
@degenerated1123 I would like to have an apk. Thanking your work. My mail is. vice09ita@gmail.com

**Comment by degenerated1123** [comment]
@vice09ita Sorry I forgot about this. We will upload an APK later today!

**Comment by degenerated1123** [comment]
There are build- and run-instructions for android now in the wiki, we've also set up CI for it, so we don't break the build again.

**Comment by vice09ita** [comment]
Many thanks!!

Il 09 ott 2017 11:12 AM, "degenerated1123" <notifications@github.com> ha
scritto:
