### ISSUE TITLE
REGoth Crash Win7 64bit

### ISSUE THREAD

**Issue by Fragy** [REGoth-project/REGoth#157]
REGoth Crashed when i used the "Gothic Beenden" Button in the Main Menu. Build: 0.3.56
![gothic crash](https://cloud.githubusercontent.com/assets/26026536/23469953/68d603b8-fea5-11e6-8f29-82bbf877bdc5.jpg)

**Comment by markusobi** [comment]
can you reproduce this crash with https://github.com/REGoth-project/REGoth/releases/tag/nightly-0.3.211?

and test if https://github.com/REGoth-project/REGoth/releases/tag/nightly-0.3.212 fixes it?
