### ISSUE TITLE
Whilst saving, hero is being moved around

### ISSUE THREAD

**Issue by tomedi** [REGoth-project/REGoth#164]
The hero doesn't stay at the very same place he was standing before the game was saved. It seems he is being randomly moved around by the saving process.

**Comment by degenerated1123** [comment]
I know that his orientation isn't currently saved. But actually moving around seems new to me.

**Comment by CppAndre** [comment]
This seems only to happen when saving through the menu not via the console command.

**Comment by markusobi** [comment]
This bug is related to the game pausing while in Menu. This bug does not occur when the game is not paused.

**Comment by markusobi** [comment]
fixed
