### ISSUE TITLE
.VDF-files are not loaded by timestamp.

### ISSUE THREAD

**Issue by superdavid639** [REGoth-project/REGoth#192]
REGoth takes the first result it can find (by alphabet) and ignores the timestamp of the other .VDF-files.
E.g. Textures.vdf is loaded before Textures_Addon.vdf. That causes REGoth to not load some textures from Gothic II NotR but from Gothic II classic.

**Comment by degenerated1123** [comment]
Loading by timestamp isn't implemented yet. Shouldn't be too hard though.

**Comment by markusobi** [comment]
Which timestamp is relevant for deciding which file to load?
The timestamp of the whole .vdf archive?
or
The timestamp of each individual file inside the vdf-file?

**Comment by nicodex** [comment]
The timestamp in the header of the VDF file (the entries in the VDF volume do not have their own timestamps).

**Comment by frabert** [comment]
The timestamp on the VDF header is correctly read by the `physfs` branch and can be accessed by calls to `PHYSFS_getLastModTime`. It is not currently implemented in the FileIndex class, but can easily be added. Though the correct way to handle this situation, if I understand it correctly, is to mount the VDF files in order of ascending timestamp, and let PhysFS manage the resolution by itself.

**Comment by tomedi** [comment]
Solved with the merge of #325 . Issue can be closed.
