### ISSUE TITLE
VS 2015 compile errors

### ISSUE THREAD

**Issue by kapitaenzufall** [REGoth-project/REGoth#206]
Hi everyone,
today I tried to compile the master branch by using cmake 3.7.1 and Visual Studio Community 2015 on/for windows.

The errors all all located inside "GameSession.cpp" and "SavegameManager.cpp".

I managed to fix some json related errors inside these files by exlizit converting json objects to strings (e.g. worldFile = worldJson["zenfile"].get<std::string>(); ). I also had to convert the strings inside the parse functioin to c-strings (e.g. newWorldJson = json::parse(worldFromDisk.c_str());) .

But l was not able to fix the following errors which are located in these files and lines:

"GameSession.cpp"
line 205: AsyncAction::executeInThread(std::move(registerWorld_), engine, ExecutionPolicy::MainThread);
line 253: AsyncAction::executeInThread(std::move(registerWorld), engine, ExecutionPolicy::MainThread);

"SavegameManager.cpp"
line 259: AsyncAction::executeInThread(std::move(registerWorld), gameEngine, ExecutionPolicy::MainThread);

Build output message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'std::_Binder<std::_Unforced,_Ty,Engine::BaseEngine>::_Binder(const std::_Binder<std::_Unforced,_Ty,Engine::BaseEngine> &)': attempting to reference a deleted function	engine	C:\Program Files\Microsoft Visual Studio 14.0\VC\include\xutility	287

**Comment by degenerated1123** [comment]
Compilling on VS2015 should "just work" and is in fact automatically tested for every commit.

Can you verify that the build fails, even with what out CI-Server does?

It uses this build-script (and VS2015):
```sh
git clone --branch=%APPVEYOR_REPO_BRANCH% --recursive https://github.com/REGoth-project/REGoth.git
cd REGoth

mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
cmake --build . --config RelWithDebInfo
```

**Comment by kapitaenzufall** [comment]
Just run the instructions from your build-script with --branch=master.

But it is not working.

http://imgur.com/a/BwrQc

**Comment by markusobi** [comment]
I'm 99,99999% sure that the compiler you are using does not support _full_ C++14

>  I also had to convert the strings inside the parse functioin to c-strings

There are some new function overloads in C++14 for `std::string` instead of the old c-strings (`const char*`). Your compiler probably doesn't support this features.


> attempting to reference a deleted function

This is because your compiler tries to copy a unique_ptr instead of moving it. C++14 now offers [Generalized lambda captures](https://isocpp.org/wiki/faq/cpp14-language#lambda-captures) which I made use of.
Seems like your compiler doesn't support some C++14 feature.

**Comment by kapitaenzufall** [comment]
Ok thanks. I'll try a newer compiler version.

**Comment by degenerated1123** [comment]
Probably you're only missing some update, because - as already stated - building does work with VS2015.

**Comment by markusobi** [comment]
AFAIK the visual studio updates are installed via the "optional" windows updates. So installing all those updates might solve it.

**Comment by kapitaenzufall** [comment]
Ok I run the optional windows updates but this will take some time I guess^^

**Comment by frabert** [comment]
Also, for now the VS2015 (v140) toolchain is the only working, since the patched v141 has not been released yet. So you have to specify v140 if you generate a VS2017 project

**Comment by ousnius** [comment]
@frabert v141 is working fine, my patches are on the master branch.

**Comment by frabert** [comment]
@ousnius Interesting, maybe I haven't received the updated version yet.

**Comment by ousnius** [comment]
@frabert I think you're referring to the "Internal compiler error"? Someone of us had fixed that issue by adjusting the code somewhere, so we didn't need to wait for Microsoft's fix for the error. Not sure what it was anymore, though.

**Comment by frabert** [comment]
@ousnius Yes, it was that. I haven't tried to compile the latest commits, so it could easily be the case.

**Comment by kapitaenzufall** [comment]
Finally I installed VS2017 and it works for me either.
Thanks for your support!

**Comment by ousnius** [comment]
@kapitaenzufall Check my guide for using the cmake integration of VS 2017 on the wiki, too. 👍

**Comment by kapitaenzufall** [comment]
@ousnius I already did, this is really nice!
