### ISSUE TITLE
Compilaton errors on MinGW

### ISSUE THREAD

**Issue by abelsromero** [REGoth-project/REGoth#217]
Hi,

I followd the instruction in the README, including the recursive clone and when compiling on Mingw (using MSYS2) the following errors appear:

https://gist.github.com/abelsromero/6094629117024c36d0337be83ecb9cc1

The first error seems related to symbol colisition* OpenAL.

* from my litle knowledge in C++

Any help will be greatly appreciated, I am just googling and trying out stuff without much idea.

**Comment by markusobi** [comment]
There seems to be some conflict with `stdio.h` and `stdlib.h`.
Try to compile this simple c-program:

**main.c:**
```
#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Hello World\n");
    return 0;
}
```

**Comment by abelsromero** [comment]
Compiled and run without problems.

> There seems to be some conflict with stdio.h and stdlib.h.

What makes you think that?

To give more info, I am using a clean installation of MSYS2 with the following packages:
- mingw-w64-x86_64-toolchain
- mingw-w64-x86_64-cmake
- git
- unzip
- mingw-w64-x86_64-SDL2

**Comment by markusobi** [comment]
There are some conflicting typedefs:
```
[ 56%] Building C object lib/openal-soft/CMakeFiles/OpenAL32.dir/OpenAL32/alAuxEffectSlot.c.obj
In file included from C:/home/bin/msys64/usr/include/stdio.h:61:0,
                 from C:/home/bin/msys64/home/my_user/temp/REGoth/lib/openal-soft/OpenAL32/Include/alMain.h:5,
                 from C:\home\bin\msys64\home\my_user\temp\REGoth\lib\openal-soft\OpenAL32\alAuxEffectSlot.c:28:
C:/home/bin/msys64/usr/include/sys/types.h:129:18: error: conflicting types for 'time_t'
 typedef _TIME_T_ time_t;
                  ^~~~~~
In file included from C:/home/bin/msys64/mingw64/x86_64-w64-mingw32/include/stddef.h:7:0,
                 from C:/home/bin/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.1.0/include/stddef.h:1,
                 from C:/home/bin/msys64/usr/include/stdlib.h:16,
                 from C:\home\bin\msys64\home\my_user\temp\REGoth\lib\openal-soft\OpenAL32\alAuxEffectSlot.c:23:
C:/home/bin/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h:138:20: note: previous declaration of 'time_t' was here
typedef __time64_t time_t;
```
`typedef _TIME_T_ time_t;`
comes from `C:/home/bin/msys64/usr/include/sys/types.h` via `C:/home/bin/msys64/usr/include/stdio.h:61:0`

`typedef __time64_t time_t;`
comes from `C:/home/bin/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h` via `C:/home/bin/msys64/usr/include/stdlib.h:16`

What in the end causes the compiler to abort compilation is the fact, that `__time64_t` resolves to a different type than `_TIME_T_` on your platform.
I.e. `__time64_t` might resolve to (signed/unsigned) long long, while `_TIME_T_` might resolve to (signed/unsigned) `int`/`long`.

So the real question is: why did it work with the hello-world example?
Did it use different headers?

Something that might be useful:
There is a simple trick to find out to which type a `typedef` or a `#define` resolves.
Just provoke a type error and the compiler will tell you the types:
```
    struct dummy {};
    struct dummy d;
    d = (time_t)0;
    d = (_TIME_T_)0;
```

**Comment by markusobi** [comment]
After having a closer look at the paths, this might be the problem:
There are two different include directories in use:
 - C:/home/bin/msys64/usr/include
 - C:/home/bin/msys64/mingw64/x86_64-w64-mingw32/include
One of them shouldn't be in the compilers include search path

**Comment by abelsromero** [comment]
> Maybe one of them shouldn't be in the compilers include search path. Do they contain the same header files?

I guess so. The `usr/include` path has some smelly includes. At some point I installed and uninstalled other packages like OpenAL via package manager and maybe something was not properly deleted. But still is odd.

Now I made a clean installation installing only `mingw-w64-x86_64-toolchain` and `mingw-w64-x86_64-cmake` and now I get other errors (luckily OpenAl is compiling now :+1: )

https://gist.github.com/abelsromero/b0e1b0dc1c0e2b91d63af3fd0337cbe1

Seems to me I need to add some flag to CMAKE to set the std++ version?

Sincerely, thanks a lot for you help,

**Comment by markusobi** [comment]
Our cmake file already adds the appropriate c++14 flag [here](https://github.com/REGoth-project/REGoth/blob/master/CMakeLists.txt#L4).
This compiler error message looks like your compiler doesn't support some c++11/c++14 feature. Check the version of your compiler. [similar problem](https://stackoverflow.com/questions/21036062/compiler-error-expected-nested-name-specifier).

Officially REGoth supports [gcc6 or later](https://github.com/REGoth-project/REGoth#building).
(I am using gcc5.4 and it's working fine)
You need a compiler with full c++14 support.

**Comment by abelsromero** [comment]
I am using gcc 7.1 and I can compile this program with C++14 features without problems (with ant without the std=c++14 flag)

```
#include<iostream>
#include<vector>
#include<numeric>
#include<algorithm>

int main()
{
	// This is c++14
    // Store a generalized lambda, that squares a number, in a variable
    auto func = [](auto input) { return input * input; };
    std::cout << func(10) << std::endl;
    std::cout << func(2.345) << std::endl;

    printf("Done!!\n");
    return 0;
}
```

I will go through the generated make files to check the flags, but I am not sure MinGW is 100% compatible with the sources.

**Comment by markusobi** [comment]
You can use `make REGoth VERBOSE=1` to see the actual call of `g++` and the passed compiler flags.

**Comment by abelsromero** [comment]
Thanks for the note, I could check the flag `std=c++14` is enable for the file. And I have been compiling many files with C++14 features without problems, but the `parse_numbers.h` just fails :/

I could compile it without any problem on Ubuntu, using gcc 6.3. And `parse_numbers.h` is exactly the same on Linux and on Windows, so it seems to be some problem with gcc 7.x.
Also I imported the project in Visual Studio 2017 and the cmake was parsed but failed dou being unable to find the C++ compiler.

Honestly, I think I quit and just try the nighlys.

**Comment by markusobi** [comment]
> it seems to be some problem with gcc 7.x.

Is there a gcc6 for Mingw?

> Also I imported the project in Visual Studio 2017 and the cmake was parsed but failed due to being unable to find the C++ compiler.

Use the Visual Studio Developer Command Prompt (there should be a shortcut in your start menu). It is like cmd.exe, but the `CXX` variable is already set to point to the microsoft compiler.

I was able to build it on windows using:
`cd build`
`cmake ..`
`cmake --build . --config Release`

**Comment by abelsromero** [comment]
Same error with MinGW toolchain 6.2 😞 

However, GOOD NEWS, I could build with `Visual Studio`, but not with the command you posted. The `Developer Command Prompt` does not appear in my programs menu, but I found the launcher in VS installation directory. But cmake (the one installed by VS) is not in the PATH.
Funny fact, cl is in the path and I can compile stuff. But after setting cmake in the path, it fails with the message
```
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.
```
So, I went back to the original MSYS shell and typed `cmake -G "Visual Studio 15 2017 Win64" ..`, and it worked. From here it DOES find cl.exe as C and CXX compiler and I could build with `cmake --build . --config release`.

**Comment by ousnius** [comment]
I didn't need to do this in my VS 2017 install, I simply opened the folder and built.

**Comment by abelsromero** [comment]
> I didn't need to do this in my VS 2017 install, I simply opened the folder and built.

I am sure of that. My Visual Studio installation comes from Unity and then I installed the C++ packages, so probably something is not 100% well configured.
But at least I was able to compile the project :smile:  I am not happy that I need to rely on Microsoft suit, but it's something.

Thanks a lot for your support. You can close this issue if you want.

**Comment by Try** [comment]
> And `parse_numbers.h` is exactly the same on Linux and on Windows, so it seems to be some problem with gcc 7.x.

Hi!
Looks like I've found the issue:
There are "logger.h" file inside ZenLib, which includes "windows.h" and overrides word __valid with it's own macro. As the result mingw headers go crazy. 

Now I want to prepare patch for ZenLib, in meantime add this lines in logger.h:
```
 #include <windows.h>
 // HACK: Work around windows.h messing this up with its define
 #ifdef DialogBox
 #undef DialogBox
 #endif
+#ifdef __valid
+#undef __valid
+#endif
```

**Comment by Try** [comment]
Small update on previous post:
  Actually problem not in ZenLib/windows.h, but in bgfx library:
bgfx-cmake\bx\include\compat\mingw\sal.h, line 15

Well, in my opinion bgfx is beyond repair...
