### ISSUE TITLE
broken graphics on MacOS

### ISSUE THREAD

**Issue by Drako** [REGoth-project/REGoth#241]
Currently, when run on macOS, the game looks like this:

<img width="1274" alt="regoth macOS" src="https://user-images.githubusercontent.com/134810/30629487-6a702c18-9ddc-11e7-805b-f3df178b24ee.png">

I would try to fix this myself, but I don't know where to start :(

I tried setting OpenGL to >3.2 Core Profile, which resulted in error messages about shader version 120 being incompatible (no surprise).
So with the old OpenGL I think I would also get errors, if the shaders could not be compiled or something, yet I didn't see any in the output.

**Comment by noahndertaler** [comment]
@degenerated1123 thought that the problem was a shader issue. There is a bug in bgfx with Metal. https://github.com/bkaradzic/bgfx/issues/1227
I don't know if this issue has anything to do with it but it might be a good starting point.

**Comment by degenerated1123** [comment]
I didn't supply any shaders compiled for metal, so it should still use opengl.

**Comment by Drako** [comment]
fyi this happens on my 2015 MacBookPro with an Intel Iris Graphics 6100 running macOS Sierra 10.12.6

Someone else mailed me, that he has the same problem and an occasional BAD_ACCESS exception form bgfx. I haven't encountered that exception myself, but interestingly he has the same hardware and OS version as me.

**Comment by noahndertaler** [comment]
The BAD_ACCESS exception was thrown when I was ingame and changed worlds/started a new game again. I think this is a different issue.

**Comment by degenerated1123** [comment]
@noahndertaler We do have a memory leak lingering around somewhere which shows itself after a few world-switches.

**Comment by ritaritual** [comment]
Have the same issue. Graphics: Intel Iris Pro 1536 MB. OS X Sierra 10.12.6 (16G29)
<img width="1440" alt="screen shot 2017-10-03 at 03 03 14 2" src="https://user-images.githubusercontent.com/12256295/31105507-62ec7e22-a7ed-11e7-9d21-c58100361663.png">

**Comment by ritaritual** [comment]
Have the same issue. Graphics: Intel Iris Pro 1536 MB. OS X Sierra 10.12.6 (16G29)
<img width="1280" alt="screen shot 2017-10-03 at 03 48 38" src="https://user-images.githubusercontent.com/12256295/31105557-cc3e0008-a7ed-11e7-849f-92f43a2d4d0f.png">

**Comment by Kukunin** [comment]
How did you get this built on MacOS ? I can't find an instruction

**Comment by Drako** [comment]
@Kukunin  try the Linux way

**Comment by Kukunin** [comment]
I compiled REGoth with latest bgfx , and I've got this: 
<img width="1440" alt="screen shot 2017-10-06 at 14 32 45" src="https://user-images.githubusercontent.com/237993/31276388-426b270c-aaa4-11e7-9353-c5d5bdd24f64.png">
It seems, new version fixes this issue, but introduces a couple new glitches

**Comment by Kukunin** [comment]
Should be fixed on latest master branch
