### ISSUE TITLE
Audio crashs game?

### ISSUE THREAD

**Issue by contra98** [REGoth-project/REGoth#242]
Happens only on one machine using linux:

On the current master branch, when I turn left or (q or e), regoth seems to play all possible sounds in the world at once, the screen turns into sky color and then the game crashs. On the FixKeyBindings branch, Regoth crashs nearly immediately, with the same only sky screen. 

The same machine and windows works fine, with both nvidia graphics and nvidia sound. 

I have the console and error output for the master branch. In the output file, on line 2350 the problems

[regoth.err.txt](https://github.com/REGoth-project/REGoth/files/1319123/regoth.err.txt)
[regoth.out.txt](https://github.com/REGoth-project/REGoth/files/1319124/regoth.out.txt)

I don't know, when the problem started, but 0.3 works fine.

On another machine (linux), with intel graphics and sound are no problems.

**Comment by markusobi** [comment]
The sky is the background afaik. If your hero is somewhere outside the map you will see only the background.
The log indicates, that ALL npcs are loaded and in range:

> Info: AISTATE-START: ZS_BOSS on NPC: Der Reislord (WP: NC_RICELORD)

This NPC shouldn't be in range.

There is also an openAL error:

> Could not create OpenAL buffer: AL_INVALID_VALUE

But since `out` and `err` are separated, I don't at which point the OpenAl error occurs. But my guess would be, that the OpenAL crash is the result of the game trying to play thousands of sounds at the same time.

So the question is: why does the game load all NPCs? is your render distance infinite? or are all npcs teleported to the same location like {`-NAN`, `-NAN`, `-NAN`}?

**Comment by contra98** [comment]
The branch FixKeyBindings doesn't help, it makes it even worse. All npc are loaded after startup and depending on the world, the game crashs or the screen turns to background but doesn't crash. Fewer NPC in there.

openAL errors seem to appear randomly, a look into the free mine:

`Info: Done!
Info: Running init_freemine
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   121: BC1 (requested: BC1), layers 1, 256x128x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   122: BC1 (requested: BC1), layers 1, 256x512x0.
Info: Done!
Info: Initialize dialog manager
Info: Loading OU-file from: /home/conrad/Playonlinux/wineprefix/Gothic_gog/drive_c/Program Files/JoWooD/Gothic//_work/Data/scripts/content/CUTSCENE/OU.BIN
Info: Creating script-side dialog-manager
Info: Zen-File found! Size: 1724531
Info: Reading...
Info: Reading 7360 blocks
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   123: BC1 (requested: BC1), layers 1, 256x128x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   124: BC1 (requested: BC1), layers 1, 256x256x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   125: BC1 (requested: BC1), layers 1, 256x256x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   126: BC1 (requested: BC1), layers 1, 256x256x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   127: BC1 (requested: BC1), layers 1, 256x256x0.
Info: Adding dialog-UI to root view
Info: Done initializing DialogManager!
Info: Script-initialization done!
Info: Done loading world!
Info: Setting camera mode to third-person
Info: Creating default player
Info: Inserting player of class 'PC_HERO' at startpoint 'zCVobStartpoint:zCVob'
Info: AISTATE-START: ZS_SITAROUND on NPC: Schatten (WP: FM_162)
Info: AISTATE-START: ZS_STANDAROUND on NPC: Schatten (WP: FM_162)
Info: AISTATE-START: ZS_ROASTSCAVENGER on NPC: Schatten (WP: FM_157)
Info: AISTATE-START: ZS_SITAROUND on NPC: Schatten (WP: FM_162)
Info: AISTATE-START: ZS_STANDAROUND on NPC: Schatten (WP: FM_162)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_89)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_105)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_103)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_102)
Info: AISTATE-START: ZS_MINEBELLOWS on NPC: Buddler (WP: FM_159)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_136)
Info: AISTATE-START: ZS_PICKORE on NPC: Buddler (WP: FM_88)
Info: AISTATE-START: ZS_WAITFORRESCUE on NPC: Ork Sklave (WP: FM_RESCUE)
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   128: BC1 (requested: BC1), layers 1, 512x512x0.
/media/Daten/conrad/Programme/REGoth/lib/bgfx-cmake/bgfx/src/renderer_gl.cpp (4890): BGFX Texture2D   129: BC1 (requested: BC1), layers 1, 256x128x0.
/media/Daten/conrad/Programme/REGoth/src/audio/AudioWorld.cpp(126):[Handle::SfxHandle World::AudioWorld::loadAudioVDF(const VDFS::FileIndex&, const string&)] Could not create OpenAL buffer: AL_INVALID_VALUE
/media/Daten/conrad/Programme/REGoth/src/audio/AudioWorld.cpp(254):[World::AudioWorld::Source World::AudioWorld::getFreeSource()] Could not allocate AL source!
Info: play sound ORC_Ambient01.wav vol 30
/media/Daten/conrad/Programme/REGoth/src/audio/AudioWorld.cpp(199):[Utils::Ticket<World::AudioWorld> World::AudioWorld::playSound(Handle::SfxHandle, const float3&, bool, float)] Could not attach buffer to source: AL_INVALID_NAME
/media/Daten/conrad/Programme/REGoth/src/audio/AudioWorld.cpp(126):[Handle::SfxHandle World::AudioWorld::loadAudioVDF(const VDFS::FileIndex&, const string&)] Could not create OpenAL buffer: AL_INVALID_VALUE
Info: play sound ORC_Ambient01.wav vol 30
Info: play sound ORC_Ambient01.wav vol 30
/media/Daten/conrad/Programme/REGoth/src/audio/AudioWorld.cpp(126):[Handle::SfxHandle World::AudioWorld::loadAudioVDF(const VDFS::FileIndex&, const string&)] Could not create OpenAL buffer: AL_INVALID_VALUE
Info: play sound ORC_Ambient01.wav vol 30
Info: play sound eat_meat.wav vol 5
Info: play sound ORC_Ambient01.wav vol 30
Info: play sound eat_bread.wav vol 5
Info: play sound ORC_Ambient01.wav vol 30
Info: play sound ORC_Ambient01.wav vol 30
`

I'll give bisect a try in the next days and maybe I'll play around with gdb.

**Comment by contra98** [comment]
It seems git messed the source up and although compiling worked well, something went wrong.

After cleaning up, Regoth works as expected. Impressing work!
