### ISSUE TITLE
[G2] Roadblock after coming back from the valley of mines

### ISSUE THREAD

**Issue by degenerated1123** [REGoth-project/REGoth#280]
The scripte variable `Kapitel` (engl. `chapter`) isn't set to `3`, which is part of the condition to talk to Lord Hagen.

**Comment by markusobi** [comment]
I found the cause:
wrong initialization/import order:
`m_ScriptEngine.importScriptEngine(scriptEngine)` is called after `initializeScriptEngineForZenWorld`.
Which means all the global vars (like `Kapitel`) are imported after (`INIT_NewWorld`)`initializeScriptEngineForZenWorld`. `INIT_NewWorld` sets the chapter.
I'm currently working on a fix.
