### ISSUE TITLE
[G2] Not possible to start Dialog (caused by "AI_SetWalkMode")

### ISSUE THREAD

**Issue by markusobi** [REGoth-project/REGoth#287]
Many NPCs (i.e. Lobart) can be no longer talked to.
The issue was introduced by branch walk-mode.
Maybe it has something to with the AI/queue.

When disabling the external "ai_setwalkmode" everything works fine.
Also "WALK" mode does not work in G2, only "RUN" works.

**Comment by degenerated1123** [comment]
Turns out G2 has a different set of animations regarding the walk-mode (ie. there is no `S_WALK`-animation). This issue should not exist in G1, right? I'll need to come up with something different to support G2...

**Comment by markusobi** [comment]
Yeah, I didn't have any problems in G1.

**Comment by degenerated1123** [comment]
Currently rewriting the animation handler... This time I'm using a better approach too, since I've learned a lot about the animations naming scheme in the last attempt.

**Comment by markusobi** [comment]
fixed by #290
