### ISSUE TITLE
[Android] Taps are not recognized

### ISSUE THREAD

**Issue by ChaosMarc** [REGoth-project/REGoth#298]
Samsung Galaxy S5 / LineageOS 14.1 (latest nightly) / Android 7.1.2

After downloading and extracting the demo or using my installed desktop game files I can launch to the Main Menu but cannot do anything there. The documentation https://github.com/REGoth-project/REGoth/wiki/Android-App tells me to tap in the upper left quadrant to simulate "Enter" but nothing happens. Tapping on other areas does nothing at all, too.

I can see the Android notification bar in front of the main menu at all times and by tipping on it the nofication center drops into view. I guess the app is not completely in full screen so my taps are not recognized.

![screenshot_20171024-110936](https://user-images.githubusercontent.com/1343751/31938114-e9f3f830-b8b6-11e7-90b1-e82ab11e1240.png)

**Comment by degenerated1123** [comment]
> I can see the Android notification bar in front of the main menu at all times and by tipping on it the nofication center drops into view. I guess the app is not completely in full screen so my taps are not recognized.

This is known behavior. It does that for me too, but the input works fine.

Are you able to compile the android version yourself? We could put some logging to see whether input is registered at all...

**Comment by ChaosMarc** [comment]
I just set up my android dev environment. compiling and installing works.

**Comment by degenerated1123** [comment]
Cool! In the newer versions of android studio, you can even set breakpoints in native code!

`PlatformAndroid.cpp`, line 273 onwards (beware, that file is not very pretty):
```cpp
                        if(x < getWindowWidth() / 2)
                        {
                            keyEvent(ACTION_PlayerAction, 0, KEY_ACTION_PRESS, 0);
                        } else
                        {
                            keyEvent(ACTION_Escape, 0, KEY_ACTION_PRESS, 0);
                        }
```

do these ever get called?

> If breakpoints do not work, you can also put a `LogInfo() << "My Message";` there

**Comment by ChaosMarc** [comment]
Thanks for the direction.
In line 190 the expression AInputEvent_getSource(event) evaluates to {int}20482 so the case AINPUT_SOURCE_TOUCHSCREEN (4096) is not true.

random guess: 20482 looks to me like 2048*2 which would be 4096 :-D
