### ISSUE TITLE
[Android] Floating Heads

### ISSUE THREAD

**Issue by ChaosMarc** [REGoth-project/REGoth#305]
With the latest build on my Samsung Galaxy S5 (Lineage 14) most 3d objects are not displayed correctly. NPCs are only shown as their heads and weapons:
![photo_2017-11-15_13-23-20](https://user-images.githubusercontent.com/1343751/32835936-54593d5e-ca08-11e7-94fc-f3d8e4f5a814.jpg)

besides that everything runs smooth (even in the old camp)

**Comment by ataulien** [comment]
That is caused by your graphics driver not supporting the high number of uniforms in the skeletal mesh shader. Doing the skeletal animation on the CPU would be a fix.

Performance has been improved by implementing proper frustum culling :smile:
