### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by devnexen** [REGoth-project/REGoth#307]
Hello, From the GitHub repo we can build all but the problem with the source code release versions, the dependencies are empty folder. Is there a script to get them or do we have to do it manually ? Thanks.

**Comment by Kukunin** [comment]
Did you do `git pull --recurse-submodules` ?

**Comment by devnexen** [comment]
I meant from a package like

https://github.com/REGoth-project/REGoth/archive/nightly-0.4.80.tar.gz

**Comment by Kukunin** [comment]
I believe that those archives contain only binaries. If you want to build it from the source codes, follow the Git cloning way

**Comment by devnexen** [comment]
Yes I m already doing it thanks
