### ISSUE TITLE
[Suggestion/Request] Option to disable Texture Filtering

### ISSUE THREAD

**Issue by veekdot** [REGoth-project/REGoth#329]
I'd like to see the option to disable Texture Filtering to be added. Early 90's 3D shooters had a kind of romantic artstyle that is lost with texture filtering. Especially with the pixelated artstyle making kind of a renaissance it'd be interesting to see how Gothic looks with it. Some screens of Quake 1 attached to give a visual representation of what I'm asking.

![2018-05-07_15-12-38_quakespasm](https://user-images.githubusercontent.com/5453361/39704266-0d9f13a8-520b-11e8-97e1-897c3b53229b.png)
![2018-05-07_15-12-58_quakespasm](https://user-images.githubusercontent.com/5453361/39704267-0dbcb368-520b-11e8-8185-2522795ec396.jpg)

**Comment by frabert** [comment]
![immagine](https://user-images.githubusercontent.com/1268384/39911262-1c6d3f8e-54fb-11e8-961b-9a18a286da57.png)

Something like this? I personally don't find it very fitting - the models are maybe not polygonal enough - but I guess it's doable

**Comment by veekdot** [comment]
Yeah exactly. Though I see your point

> the models are maybe not polygonal enough

If having the option **doesn't** hurt I'd like to see it in :D
