### ISSUE TITLE
Audio isn't working anymore

### ISSUE THREAD

**Issue by benjaminfoo** [REGoth-project/REGoth#33]
Since a few commits, the audio seems to be disabled or not working. I'm using a Conexant 20672 SmartAudio HD Chip on a X220 thinkpad, running a Windows 10 operating system.

**Comment by degenerated1123** [comment]
It did work the last time I tried (on linux). Are you building from source?
Because if so, you need the openal32.dll (With the right architecture! Nightly-Builds are 32-bit!) in the working-directory of the executable. If it's not there, sound will simply not work. If it has the wrong arch, it may work, but may also crash before actually starting the program.

You can grab it from `lib/SFML/extlibs/bin/<arch>`. Does that maybe help?

**Comment by benjaminfoo** [comment]
By adding the named dll for the x86 architecture on windows 10, the executable is running but the sound seems like to be muted.

**Comment by degenerated1123** [comment]
Update: Audioengine is currently being completely reworked.

**Comment by astillich** [comment]
Rework is done @benjaminfoo can you test again please?

**Comment by astillich** [comment]
I have tested the sound stuff on two Linux systems and one Win 10 system. Please file another bug report if there are problems with the new audio implementation. Closed because reporter did not respond and the issue is related to a library we don't use anymore.

**Comment by benjaminfoo** [comment]
Sorry for the delay, studiyng is consuming my time. I still have no hearable audio on windows 10.

**Comment by astillich** [comment]
OK, I'll reopen the issue ... will be able to compile / debug on windows soon and see if I can reproduce it. Do you have other [games](https://www.openal.org/games/) to test?

**Comment by benjaminfoo** [comment]
So I tested openarea, which uses OpenAL and it gave me the full sound experience. I will investigate further into this.

**Comment by astillich** [comment]
Does it log which device it uses? You could try passing that to the -snd command line option, probably quoted: "DEVICE NAME".

**Comment by benjaminfoo** [comment]
I've found the following in the startup logs of the engine: C:\dev\REGoth\src\audio\AudioEngine.cpp(61):[__thiscall Audio::AudioEngine::AudioEngine(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)] Could not open audio device ''sound-device'': AL_INVALID_OPERATION, sound disabled

**Comment by benjaminfoo** [comment]
Well, the speech-audio works after removing my installation of OpenAL from my system, but is the background sfx support?

Anyhow, great work!

**Comment by astillich** [comment]
Just speech and taking notes and leveling up ATM.

**Comment by benjaminfoo** [comment]
Great, I guess this can be closed now :).
