### ISSUE TITLE
Fire Effect changes depending on distance to fire

### ISSUE THREAD

**Issue by MaxGitHubAccount** [REGoth-project/REGoth#330]
Linked to #65 
Probably also linked to #272 

**REGoth Information**
Version: commit 59cef91855084b53e8d1cf7e67197ed66ad1674e (HEAD -> master, origin/master, origin/HEAD)
Start command: ./REGoth -g /var/games/Gothic\ II -w newworld.zen

**PC Information**
uname -r: system: 4.16.7-1-ARCH
Desktop: KDE-Plasma v5.12
lspci -v: 
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:02.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
00:03.0 SCSI storage controller: Red Hat, Inc. Virtio block device
00:05.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
-- (Kernel driver in use: nvidia)
00:06.0 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
00:07.0 USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller (rev 03)

**Steps to reproduce**

1. Go to any fire in the world (e.g. at onars farm or in Khorinis)
2. Look at a fire from distance
3. Go nearer to the fire

**Expected behaviour**

2. The fire looks correct
3. The same fire animation as in 2.

**Observed behaviour**

2. The fire is pixeled (like blocks) and white
![screenshot_20180511_102059-fire-effect](https://user-images.githubusercontent.com/476371/39914963-d7199caa-5506-11e8-80fb-94dd8b148562.png)
![screenshot_20180511_102219-fire-effect-2](https://user-images.githubusercontent.com/476371/39915229-a1fed0ac-5507-11e8-8f14-2575c76ce0a1.png)

3. The fire receives it's correct form and colour

![screenshot_20180511_102234-fire-effect-correct](https://user-images.githubusercontent.com/476371/39915331-f0d54d5a-5507-11e8-96d0-3cbce0d266eb.png)

**Comment by ataulien** [comment]
This doesn't seem like a lighting issue, but rather the particles reacting wrong to the fog.

**Comment by MaxGitHubAccount** [comment]
I can reproduce the same in Gothic
![screenshot_20180511_123313-fire](https://user-images.githubusercontent.com/476371/39920517-980dedde-5517-11e8-873d-9273604f3932.png)

**Comment by tomedi** [comment]
I've got the same issue! Also Nvdia Gtx, but 860m.
