### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by MaxGitHubAccount** [REGoth-project/REGoth#334]
As a user I want to play Gothic in fullscreen mode to be completely focussed on the game as in the vanilla game.

Gothic and Gothic II are full screen in vanilla. REGoth currently opens in windowed mode. While it's cool to also have a windowed mode, normally it would be nice to play in fullscreen. Maybe there could be an option in the settings (see #333) video where the preferred window mode could be toggled from window mode to fullscreen.

**Comment by frabert** [comment]
Just to be clear, you can start REGoth in full screen mode using `-f`

**Comment by MaxGitHubAccount** [comment]
Ok thanks for the information. I will close this :)
