### ISSUE TITLE
Main menu: Detect Gothic II: Night of the Raven

### ISSUE THREAD

**Issue by MaxGitHubAccount** [REGoth-project/REGoth#335]
As a user I want to see the Night of the Raven main menu background and heading image (headline) in the main menu in order to know that I will play Gothic II with the expansion. This should of cause only appear if I have Night of the Raven data and not if I only have Gothic II data.

**Comment by MaxGitHubAccount** [comment]
I have found the pull request for it #325

**Comment by ChaosMarc** [comment]
This issue was fixed in #325 and can be closed
