### ISSUE TITLE
Switch to OpenAL

### ISSUE THREAD

**Issue by astillich** [REGoth-project/REGoth#39]
Working on it. Also laying some basics for 3D sound, though I'll probably not fully implement it ATM.

**Comment by degenerated1123** [comment]
Sounds great! SFML is too big of a dependency for just playing sounds, so this is a nice change.

By the way, we have a chatroom on Gitter where we can discuss such things: https://gitter.im/REGoth/Lobby
Maybe you want to join?

**Comment by astillich** [comment]
Yeah, a place to chat is nice. Tickets are not the appropriate place. But this an isolated problem and I don't have any questions ATM. We can discuss the implementation when I send the PR. Or do you have something in mind I should pay attention to?

**Comment by degenerated1123** [comment]
No, just wanted to let you know! Looking forward to the PR!
