### ISSUE TITLE
Animation Events

### ISSUE THREAD

**Issue by astillich** [REGoth-project/REGoth#59]
Implement animation events.

**Comment by astillich** [comment]
Restructured the animation stuff in ZenLib so that it is split between MDS / MSB (Model Script) and actual animation data (MAN). Factored out parsing code into separated classes from the data classes. Implemented basic MSB parsing, this will allow G2 to work. Still have to write an MDS parser for G1, though.

Started writing an AnimationLibrary which stores animations in an application-internal format: each of the animation "variations" have unique parameters and share keyframe data (.MAN). Should be able to complete and integrate soon, oh I have the code in my own forks out of habit. ;)

**Comment by degenerated1123** [comment]
You're really doing some work here! Sounds great!

**Comment by degenerated1123** [comment]
This was implemented.
