### ISSUE TITLE
Animation Sounds

### ISSUE THREAD

**Issue by astillich** [REGoth-project/REGoth#60]
Implement sounds being played by applications.

**Comment by Seegras** [comment]
Is there sound at all? It says "Info: Creating AudioWorld" but apart from that, nothing. Or could it be that it must be specified in a special way as --sound-device parameter?

**Comment by degenerated1123** [comment]
There is! Didn't NPCs speak to you? There is also a sound on levelup or when you get a new quest.

**Comment by degenerated1123** [comment]
This was implemented.
