### ISSUE TITLE
Wayland support missing

### ISSUE THREAD

**Issue by Lubieerror** [REGoth-project/REGoth#68]
I tried compile it on Fedora 25 x64 (fresh updates installed while beafore) and I when it tries use X11 for window creation I have error: 

> "CMake Error at lib/glfw/CMakeLists.txt:249 (message):
>   The RandR library and headers were not found"

Tried in tag [nightly-0.1.148](https://github.com/REGoth-project/REGoth/tree/nightly-0.1.148) (I tried it first because if I'm right master have/had build error) and [master](https://github.com/REGoth-project/REGoth/tree/master).

F25 uses Wayland so I think it may by that. Also I have nouvenau drivers because of that (nvidia support W but F25's Gnome don't have bus etc. etc.) and yes I have Xwayland installed.

logs:
For [master](https://github.com/REGoth-project/REGoth/tree/master)
[CMakeError.log](http://pastebin.com/VWLNNuiZ)
[CMakeOutput.log](http://pastebin.com/ca7mPip9)

For [nightly-0.1.148](https://github.com/REGoth-project/REGoth/tree/nightly-0.1.148)
[CMakeError.log](http://pastebin.com/xdgw9JiS)
[CMakeOutput.log](http://pastebin.com/S5nEjuhv)

and screen:

![screenshot from 2017-01-13 15-28-59](https://cloud.githubusercontent.com/assets/11427815/21933960/da801166-d9a7-11e6-857c-07e9626b07f7.png)

**Comment by Lubieerror** [comment]
I almost forgot. 
> cmake version: 3.6.2
> gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

**Comment by degenerated1123** [comment]
We have a page in the Wiki for building on Fedora: https://github.com/REGoth-project/REGoth/wiki/How-To-Build
Maybe you don't need every single package, but that should cover you.

Why is Vulcan a problem?

**Comment by jangernert** [comment]
Wayland is not a problem. Running fine on my Fedora 25 machine in the wayland session.

**Comment by Lubieerror** [comment]
@degenerated1123 Not Vulcan, Wayland... sorry I was hurry up. And I didn't know about it. I builded from the Readme.md page. I'll try that way and post results.

**Comment by Lubieerror** [comment]
@degenerated1123 @jangernert You were right. I should check more deep. Build failed on X11, I read that RandR is something about displaying, on Manjaro I only had to install sfml, so I had wrong thought that It's all fault Fedora's Wayland, sorry my bad D:
